# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddCommentTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addCommentTest(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(550, 691)
    self.driver.find_element(By.LINK_TEXT, "Читати далі →").click()
    self.driver.find_element(By.LINK_TEXT, "зареєструйтесь").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.LINK_TEXT, "⬅ На головну").click()
    self.driver.find_element(By.LINK_TEXT, "Titel 1").click()
    self.driver.find_element(By.LINK_TEXT, "← На головну").click()
    self.driver.find_element(By.LINK_TEXT, "🚀 Мій Блог").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-center").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-subtitle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-subtitle").click()
    self.driver.find_element(By.LINK_TEXT, "Увійти").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("Admin4life!")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Читати далі →").click()
    self.driver.find_element(By.ID, "id_text").click()
    self.driver.find_element(By.ID, "id_text").send_keys("this is the third comment!")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(5) .text-muted").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(5) strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-title").click()
    self.driver.find_element(By.LINK_TEXT, "← На головну").click()
    self.driver.find_element(By.LINK_TEXT, "Titel 1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card-title").click()
    self.driver.find_element(By.LINK_TEXT, "← На головну").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-light").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
  
